export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/alsterg/shofer.dev",
	GITHUB_DISCUSSIONS: "https://github.com/alsterg/shofer.dev/discussions",
	DISCORD: "https://discord.gg/shofer",
	REDDIT: "https://reddit.com/r/Shofer",
	X: "https://x.com/shofer",
	LINKEDIN: "https://www.linkedin.com/company/shofer-code",
	TIKTOK: "https://www.tiktok.com/@shofer.code",
	BLUESKY: "https://bsky.app/profile/shofer.bsky.social",
	YOUTUBE: "https://www.youtube.com/@ShoferYT",
	DOCUMENTATION: "https://docs.shofer.com",
	SLACK_DOCS: "https://docs.shofer.com/shofer-code-cloud/slack-integration",
	CAREERS: "https://careers.shofer.com",
	ISSUES: "https://github.com/alsterg/shofer.dev/issues",
	FEATURE_REQUESTS: "https://github.com/alsterg/shofer.dev/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/alsterg/shofer.dev/discussions",
	CHANGELOG: "https://github.com/alsterg/shofer.dev/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/alsterg/shofer.dev/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.shofer.com/community",
	TUTORIALS: "https://docs.shofer.com/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=Shofer.dev",
	SECURITY: "https://trust.shofer.com",
	EVALS: "https://shofer.com/evals",
	BLOG_SUBSTACK: "https://blog.shofer.com",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@ShoferYT/podcasts",
	FAQ: "https://shofer.com/#faq",
	TESTIMONIALS: "https://shofer.com/#testimonials",
	CLOUD_APP_LOGIN: "https://app.shofer.com/sign-in",
	CLOUD_APP_SIGNUP: "https://app.shofer.com/sign-up",
	CLOUD_APP_SIGNUP_HOME: "https://app.shofer.com/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_SIGNUP_PRO: "https://app.shofer.com/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_TEAM_TRIAL: "https://app.shofer.com/checkout/team",
	SUPPORT: "mailto:support@shofer.com",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
	BLOG: "/blog",
}
