export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/shofer-dev/shofer",
	DISCORD: "https://discord.gg/shofer",
	REDDIT: "https://reddit.com/r/Shofer",
	X: "https://x.com/shofer",
	LINKEDIN: "https://www.linkedin.com/company/shofer-code",
	TIKTOK: "https://www.tiktok.com/@shofer.code",
	BLUESKY: "https://bsky.app/profile/shofer.bsky.social",
	YOUTUBE: "https://www.youtube.com/@ShoferYT",
	DOCUMENTATION: "https://docs.shofer.dev",
	SLACK_DOCS: "https://docs.shofer.dev/shofer-code-cloud/slack-integration",
	CAREERS: "https://careers.shofer.dev",
	ISSUES: "https://github.com/shofer-dev/shofer/issues",
	FEATURE_REQUESTS: "https://github.com/shofer-dev/shofer/discussions/categories/feature-requests",
	CHANGELOG: "https://github.com/shofer-dev/shofer/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/shofer-dev/shofer/blob/main/PRIVACY.md",
	TUTORIALS: "https://docs.shofer.dev/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=Shofer.dev",
	SECURITY: "https://trust.shofer.dev",
	EVALS: "https://shofer.dev/evals",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@ShoferYT/podcasts",
	FAQ: "https://shofer.dev/#faq",
	TESTIMONIALS: "https://shofer.dev/#testimonials",
	CLOUD_APP_LOGIN: "https://app.shofer.dev/sign-in",
	CLOUD_APP_SIGNUP: "https://app.shofer.dev/sign-up",
	CLOUD_APP_SIGNUP_HOME: "https://app.shofer.dev/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_SIGNUP_PRO: "https://app.shofer.dev/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_TEAM_TRIAL: "https://app.shofer.dev/checkout/team",
	SUPPORT: "mailto:support@shofer.dev",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
}
