blank_issues_enabled: false
contact_links:
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=Shofer.dev&ssr=false#review-details
      about: Enjoying Shofer? Leave a review here!
