export { solidityQuery } from "./solidity.js"
export { default as phpQuery } from "./php.js"
export { vueQuery } from "./vue.js"
export { default as typescriptQuery } from "./typescript.js"
export { default as tsxQuery } from "./tsx.js"
export { default as pythonQuery } from "./python.js"
export { default as javascriptQuery } from "./javascript.js"
export { default as javaQuery } from "./java.js"
export { default as rustQuery } from "./rust.js"
export { default as rubyQuery } from "./ruby.js"
export { default as cppQuery } from "./cpp.js"
export { default as cQuery } from "./c.js"
export { default as csharpQuery } from "./c-sharp.js"
export { default as goQuery } from "./go.js"
export { default as swiftQuery } from "./swift.js"
export { default as kotlinQuery } from "./kotlin.js"
export { default as cssQuery } from "./css.js"
export { default as elixirQuery } from "./elixir.js"
export { default as htmlQuery } from "./html.js"
export { default as luaQuery } from "./lua.js"
export { ocamlQuery } from "./ocaml.js"
export { tomlQuery } from "./toml.js"
export { default as systemrdlQuery } from "./systemrdl.js"
export { default as tlaPlusQuery } from "./tlaplus.js"
export { zigQuery } from "./zig.js"
export { default as embeddedTemplateQuery } from "./embedded_template.js"
export { elispQuery } from "./elisp.js"
export { scalaQuery } from "./scala.js"
